stages:
  - build

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

build-docker:
  stage: build
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  only:
    - master
    - develop
  before_script:
    - docker info
  script:
    - sh build-docker/build.sh
