stages:
  - build

variables:
  DOCKER_TLS_CERTDIR: ""

build-docker:
  stage: build
  image: docker:latest
  only:
    - master
    - develop
  services:
    - name: docker:dind
      command:
        - --insecure-registry=10.0.2.15:5050
  before_script:
    - docker info
  script:
    - build-docker/build.sh
