version: "3.5"
services:
  testing-web:
    container_name: my-test-web
    image: ${REGISTRY}/tests/testing-web:${TESTING_WEB_TAG}
    ports:
      - 9000:9000
    command:
      - "--server.port=9000"
    networks:
      - vm_net
    restart: always
networks:
  vm_net:
