version: "3.5"
services:
  testing-web:
    container_name: my-test-web
    image: ${REGISTRY}/tests/testing-web:${TESTING_WEB_TAG}
    ports:
      - 8081:8081
    command:
      - "--server.port=8081"
    networks:
      - vm_net
    restart: always
    env_file: .env
networks:
  vm_net:
