name: CI/CD

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: maven-v2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-

      - name: Build
        run: mvn clean package

      - name: Build Docker image
        run: docker build -t test-app .
